apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
  {{- include "charts.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "charts.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix