apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
type: Opaque
data:
  django-secretkey : {{ .Values.django.secretKey }}