image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<AWS_ECR_REPO_NAME>
  pullPolicy: IfNotPresent
  tag: "latest"
  containerPort: 8000
labels:
  env: "staging"
service:
  port: 8000
  targetPort: 8000
  type: LoadBalancer
replicaCount: 1
ingress:
  enabled: false
django:
  secretKey: "default-secret-key"
  databaseName: "default-database-name"
# imagePullSecrets:
#   - name: regcred
autoscaling:
  enabled: true  
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
persistence:
  enabled: true
  name: efs-claim
  storageClassName: efs-sc
  accessMode: ReadWriteMany
  size: 5Gi
