image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<AWS_ECR_REPO_NAME>
  pullPolicy: IfNotPresent
  tag: "latest"
labels:
  env: "staging"
service:
  port: 8000
  targetPort: 8000
  type: LoadBalancer
replicaCount: 1
ingress:
  enabled: false
# imagePullSecrets:
#   - name: regcred
autoscaling:
  enabled: true  
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
persistence:
  enabled: true
  name: demo-pvc
  storageClassName: gp2
  accessMode: ReadWriteMany
  size: 1Gi